config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  get '/how-to-play',   to: 'static_pages#how_to_play'
  get '/cardz',         to: 'static_pages#cardz'
  get '/board-games',   to: 'static_pages#board_games'
  get '/downloads',     to: 'downloads#downloads'
  
  get 'testerino',      to: 'static_pages#test_cardz'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :detect_device_variant
  
  private
    
  def detect_device_variant
    request.variant = :phone if browser.device.mobile?
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
  
  def modal
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns title of page
    def full_title(page_title = '')
        base_title = "Larz Cardz"
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/downloads/_age_check.html.erb
<div class="center">
<div class="container">
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-cardz" data-toggle="modal" data-target="#myModal">Download the Cardz!</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <div class="center">
            <h2 class="modal-title">Please verify your age</h2>
            <h5>Are you over 21 years in age?</h5>
          </div>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-6">
                <%= link_to "Yes", downloads_path %>
            </div>
            <div class="col-md-6">
                <div data-dismiss="modal"><%= link_to "No", "#" %></div>
            </div>
        </div>
        </div>
      </div>
      
    </div>
  </div>
</div>
</div>

app/views/downloads/downloads.html.erb
 <div class="center">
 <h3><b><%= link_to "Download the Cardz!", "/LarzCardzImagesJPG.zip" %></b></h3>
 </div>

app/views/layouts/_application_layout.html.erb
<body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <% #debug(params) if Rails.env.development? %>
    </div>
</body>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
  <div class container="container-fluid">
    <div class="col-6" id="logo">Larz Cardz</div>
      <div class="row">
        <div class="center">
          <div class="col-6 col-sm-3"><%= link_to "Home", root_path, id: "logo-three"  %></div>
          <div class="col-6 col-sm-3"><%= link_to "How To Play", how_to_play_path, id: "logo-three" %></div>
          <div class="col-6 col-sm-3"><%= link_to "Cardz", cardz_path, id: "logo-three"  %></div>
          <div class="col-6 col-sm-3"><%= link_to "Board Games", board_games_path, id: "logo-three"  %></div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_phone_header.html.erb
<header class="navbar navbar-default navbar-static-top">
  <div class container="container-fluid">
    <div class="col-6" id="logo">Larz Cardz</div>
        <div class="center">
          <div class="col-6 col-sm-3"><%= link_to "Home", root_path, id: "logo-three"  %></div>
          <div class="col-6 col-sm-3"><%= link_to "How To Play", how_to_play_path, id: "logo-three" %></div>
          <div class="col-6 col-sm-3"><%= link_to "Cardz", cardz_path, id: "logo-three"  %></div>
          <div class="col-6 col-sm-3"><%= link_to "Board Games", board_games_path, id: "logo-three"  %></div>
        </div>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/phone_header' %>
  </head>
    <body>
    <%= render 'layouts/application_layout' %>
</body>
</html>

<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/header' %>
  </head>
  <div id="modal-window" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
  <body>
    <%= render 'layouts/application_layout' %>
  </body>
</html>

<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

app/views/static_pages/_cardz_slideshow.html.erb
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-dark pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-dark next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="links">
    <a href="/assets/PounceOnIt.jpg", data-gallery>
        <img src="/assets/demcardz.png" alt="Dem Cardz Boi">
    </a>
    <a href="/assets/NewHat.jpg" data-gallery></a>
    <a href="/assets/LarzChallenge8.jpg" data-gallery></a>
    <a href="/assets/HotDamn.jpg" data-gallery></a>
    <a href="/assets/DanHossScienceChoice.jpg" data-gallery></a>
    <a href="/assets/Can'tWait.jpg" data-gallery></a>
    <a href="/assets/BananaTiem.jpg" data-gallery></a>
    <a href="/assets/Acting102.jpg" data-gallery></a>
</div>

app/views/static_pages/board_games.html+phone.erb
<% provide(:title, "Cardz") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <div class="center">
        <h3>
            <u>
                <b>Coming Soon!</b>
            </u>
        </h3>
    </div>
</meta>

app/views/static_pages/board_games.html.erb
<% provide(:title, "Cardz") %>

<h3>
    <u>
        <b>Coming Soon!</b>
    </u>
</h3>

app/views/static_pages/cardz.html+phone.erb
<% provide(:title, "Cardz") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <div class="center">
        <h3>
            <u>
                <b>THE ALPHA DECK</b>
            </u>
        </h3>
        <h3><b><%= render "downloads/age_check" %></b></h3>
        <h3>
            <u>
                <b>-144 Cards-</b>
            </u>
        </h3>
        <h3>
            Updated Deck Coming Extremely Soon
        </h3>
        <br />
        <p>Our state of the art, purist, modern, black and white design is sure to wow.</p>
        <br />
        <p>
            The Alpha deck is filled with crazy weird cards for
            your friends to go wild with. There are more than enough
            for hours of gameplay.
        </p>
        <br />
         <%= image_tag("Acting102.jpg", :alt => "Acting 102") %>
        <br />
        <p>
            <div id="small">Some are easy going.</div> 
            <div id="small">Some are typical party vibin’.</div>
            <div id="small">Some are pretty zany.</div>
            <div id="small">Some are gross.</div>
            <div id="small">Fun!</div>
        </p>
        <br />
        <%= image_tag("HotDamn.jpg", :alt => "Hot Damn") %>
        <br />
        <%= image_tag("BananaTiem.jpg", :alt => "Acting 102") %>
        <br />
        <%= image_tag("DanHossScienceChoice.jpg", :alt => "Acting 102") %>
        <br />
        <p>
            <div id="small">
                No participant in the LarzCardz experience must perform any action listed on any card 
                nor should they be pressured into doing so. The game is intended to be a fun experience 
                for all players. LarzCardz and its affiliates take no responsibility for any actions performed 
                by participants in relation to the game and cards involved. LarzCardz is intended for those who 
                are of legal drinking age. Always drink responsibly. LarzCardz and its affiliates do not condone 
                alcohol abuse. Do not drink to excess or drink and drive.
            </div>
        </p>
    </div>
</meta>

app/views/static_pages/cardz.html.erb
<% provide(:title, "Cardz") %>

<br />
<div class container="container-fluid">
    <div class="center">
        <h3>
            <u>
                <b>THE ALPHA DECK - 144 Cards</b>
            </u>
        </h3>
        <h3><b><%= render "downloads/age_check" %></h3></b>
        <h3>
            ***Updated Deck Coming Extremely Soon***
        </h3>
        <br />
        <p>Our state of the art, purist, modern, black and white design is sure to wow.</p>
        <br />
        <p>
            The Alpha deck is filled with crazy weird cards for
            your friends to go wild with. There are more than enough
            for hours of gameplay.
        </p>
            <div class="row">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <%= image_tag("Acting102.jpg", :alt => "Acting 102") %>
                </div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <p>
                        <div id="small">Some are easy going.</div> 
                        <div id="small">Some are typical party vibin’.</div>
                        <div id="small">Some are pretty zany.</div>
                        <div id="small">Some are gross.</div>
                        <div id="small">Fun!</div>
                    </p>
                    <%= image_tag("HotDamn.jpg", :alt => "Hot Damn") %>
                </div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <%= image_tag("WellThisIsWeird.jpg", :alt => "Well This Is Weird") %>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <%= image_tag("BananaTiem.jpg", :alt => "Acting 102") %>
                </div>
                 <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <%= image_tag("combocardz.jpg", :alt => "Franken Larz, Banana Tiem") %>
                </div>
                 <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <%= image_tag("DanHossScienceChoice.jpg", :alt => "Acting 102") %>
                </div>
            </div>
            <br />
            <p>
                <div id="small">
                    No participant in the LarzCardz experience must perform any action listed on any card 
                    nor should they be pressured into doing so. The game is intended to be a fun experience 
                    for all players. LarzCardz and its affiliates take no responsibility for any actions performed 
                    by participants in relation to the game and cards involved. LarzCardz is intended for those who 
                    are of legal drinking age. Always drink responsibly. LarzCardz and its affiliates do not condone 
                    alcohol abuse. Do not drink to excess or drink and drive.
                </div>
            </p>
    </div>
</div>

app/views/static_pages/home.html+phone.erb
<% provide(:title, "Home") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <div class="center">
        <p>
            LarzCardz is a weird party game for you and your friends. It combines all the fun of a normal party game, but introduces weird things, challenges and scenarios and gets rid
            of all the annoying thinking you have to do with other games.
        </p>
        <br />
        <%= image_tag("WebImage2.jpg", :alt => "Creepy Larz") %>
        <p>
            When playing LarzCardz there are fun things like:
        </p>
        <div class="col-md-6">
            <p>- Licking -</p>
            <p>- Screaming -</p>
            <p>- Physical Challenges -</p>
            <p>- Mental Challenges -</p>
            <p>- Running -</p>
            <p>- Acting -</p>
            <p>- Seducing -</p>
            <p>- Calling Your Dad -</p>
        </div>
        <br />
        <p>
            On top of being a crazy fun game, it’s a mediocre icebreaker too. So get out there and become the larz of your dreams!
        </p>
        <%= image_tag("WebImage5.jpg", :alt => "Butterfly Larz") %>
    </div>            
</meta>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<br />
<div class container="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <p>
LarzCardz is a weird party game for you and your friends. It combines all the fun of a normal party game, but introduces weird things, challenges and scenarios and gets rid
of all the annoying thinking you have to do with other games.
            </p>
            
            <br />

            <p>
                When playing LarzCardz there are fun things like:
            </p>
            <div class="col-md-6">
                    <p>- Licking</p>
                    <p>- Screaming</p>
                    <p>- Physical Challenges</p>
                    <p>- Mental Challenges</p>
                    <p>- Running</p>
                    <p>- Acting</p>
                    <p>- Seducing</p>
                    <p>- Calling Your Dad</p>
            </div>
            <div class="row">
                <br />
                <br />
                <br />
                <br />
                <div class="col-align-self-end">
                    <%= image_tag("WebImage2.jpg", :alt => "Creepy Larz") %>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <%= image_tag("lzg.jpg", :alt => "Jacked Larz with Girraffe") %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p>
                On top of being a crazy fun game, it’s a mediocre icebreaker too. So get out there and become the larz of your dreams!
            </p>
            <div>
                <%= image_tag("WebImage5.jpg", :alt => "Butterfly Larz") %>
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <%= image_tag("WebImage4.jpg", :alt => "Sandwich") %>
            </div>
        </div>
        <div class="col-md-6">
 
        </div>
    </div>
</div>

</div>

 
 
 

app/views/static_pages/how_to_play.html+phone.erb
<% provide(:title, "How To Play") %>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <div class="center">
        <h3>
            <u>How to play</u>
        </h3>
        <p>step 1:</p>
        <p>Be enthusiastic</p>
        <br />
        <p>step 2:</p>
        <p>Let go of all your fears</p>
        <br />
        <p>step 3:</p>
        <p>Draw a card and read what the gods have dealt you</p>
        <p>or</p>
        <p>Get a little spicy and deal hands to each player.</p>
        <p>
            On a player’s turn they get to give a card from their hand to any
            other player they want. The chosen one must do whatever’s on their card.
        </p>
        <br />
        <p>
            For all modes of play, whoever draws the first Larz-Designated card out of the
            deck, immediately becomes the first Larz. The instructions on the card are void,
            becoming the Larz is all the person must do.
        </p>
        <h3>
            <u>types of cards</u>
        </h3>
        <br />
        <p>
            <u>Standard</u>
        </p>
        <%= image_tag("Can'tWait.jpg", :alt => "Can't Wait") %>
        <p>
            <div id="small">Read these cards aloud and</div> 
            <div id="small">follow the instructions.</div>
        </p>
        <br />
        <p>
            <u>Do Not Read Aloud</u>
        </p>
        <%= image_tag("PounceOnIt.jpg", :alt => "Pounce On It") %>
        <p>
            <div id="small">Do not read these cards aloud.</div>
            <div id="small">Read them to yourself and place them</div>
            <div id="small">facedown in front of you until you</div>
            <div id="small">complete the instructions listed.</div>
        </p>
        <br />
        <p>
            <u>or</u>
        </p>
        <%= image_tag("XXX.jpg", :alt => "Or Card") %>
        <p>
            <div id="small">Read these cards aloud and choose</div>
            <div id="small">one of the options listed.</div>
        </p>
        <br />
        <p>
            <u>Larz-Designated</u>
        </p>
        <%= image_tag("NewHat.jpg", :alt => "New Hat") %>
        <p>
            <div id="small">Whoever is the Larz must perform the</div> 
            <div id="small">finstructions on these cards.</div>
            <div id="small">(I.E. give you their underwear)</div>
        </p>
        <br />
        <p>
            <u>Larz Challenge</u>
        </p>
        <%= image_tag("LarzChallenge8.jpg", :alt => "Larz Challenge #8") %>
        <p>
            <div id="small">You and the Larz must perform the</div>
            <div id="small">instructions on these cards. Stakes of</div>
            <div id="small">the challenge are listed on each card.</div>
        </p>
    </div>
</meta>

app/views/static_pages/how_to_play.html.erb
<% provide(:title, "How To Play") %>

<br />
<div class container="container-fluid">
    <div class="center">
        <h2>
            <u>How to play</u>
        </h2>
        <p>step 1:</p>
        <p>Be enthusiastic</p>
        <br />
        <p>step 2:</p>
        <p>Let go of all your fears</p>
        <br />
        <p>step 3:</p>
        <p>Draw a card and read what the gods have dealt you</p>
        <br />
        <p>or</p>
        <p>Get a little spicy and deal hands to each player.</p>
        <p>On a player’s turn they get to give a card from their hand to any</p>
        <p>other player they want. The chosen one must do whatever’s on their card.</p>
        <br />
        <br />
        <p>
            <u>types of cards</u>
        </p>
    
        <div class="row">
            <div class="col-md-6">
                <p>
                    <u>Standard</u>
                </p>
                <%= image_tag("Can'tWait.jpg", :alt => "Can't Wait") %>
                <p>
                    <div id="small">Read these cards aloud and</div> 
                    <div id="small">follow the instructions.</div>
                </p>
            </div>
            <div class="w-100 d-inline-block"></div>
            <div class="col-md-6">
                <p>
                    <u>Do Not Read Aloud</u>
                </p>
                <%= image_tag("PounceOnIt.jpg", :alt => "Pounce On It") %>
                <p>
                    <div id="small">Do not read these cards aloud.</div>
                    <div id="small">Read them to yourself and place them</div>
                    <div id="small">facedown in front of you until you</div>
                    <div id="small">complete the instructions listed.</div>
                </p>
            </div>
        </div>
        <div>
            <p>
                <u>or</u>
            </p>
            <%= image_tag("XXX.jpg", :alt => "Or Card") %>
            <p>
                <div id="small">Read these cards aloud and choose</div>
                <div id="small">one of the options listed.</div>
            </p>
            
            <p>
                For all modes of play, whoever draws the first Larz-Designated card out of the
                deck, immediately becomes the first Larz. The instructions on the card are void,
                becoming the Larz is all the person must do.
            </p>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <p>
                    <u>Larz-Designated</u>
                </p>
                <%= image_tag("NewHat.jpg", :alt => "New Hat") %>
                <p>
                    <div id="small">Whoever is the Larz must perform the</div> 
                    <div id="small">finstructions on these cards.</div>
                    <div id="small">(I.E. give you their underwear)</div>
                </p>
            </div>
            <div class="w-100 d-inline-block"></div>
            <div class="col-md-6">
                <p>
                    <u>Larz Challenge</u>
                </p>
                <%= image_tag("LarzChallenge8.jpg", :alt => "Larz Challenge #8") %>
                <p>
                    <div id="small">You and the Larz must perform the</div>
                    <div id="small">instructions on these cards. Stakes of</div>
                    <div id="small">the challenge are listed on each card.</div>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/test_cardz.html.erb
<div class="center">
<%= render 'cardz_slideshow' %>
</div>